import { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'de';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  de: {
    // Navbar
    'nav.howItWorks': 'So funktioniert es',
    'nav.products': 'Produkte',
    'nav.pricing': 'Preise',
    'nav.demo': 'Demo',
    'nav.contact': 'Kontakt',
    'nav.login': 'Anmelden',
    'nav.getStarted': 'Jetzt starten',

    // Hero
    'hero.headline': 'Verpassen Sie nie wieder einen Kunden.',
    'hero.subheadline': 'Ihr 24/7 KI-Rezeptionist — KI-gestützt, in Deutschland gehostet.',
    'hero.compliance': '100% DSGVO-konform',
    'hero.bullet1': 'Telefonanrufe',
    'hero.bullet2': 'WhatsApp & Chat',
    'hero.bullet3': 'Auto-Buchung',
    'hero.cta': 'Demo buchen',
    'hero.trust': '🇩🇪 Gehostet in Frankfurt • 🔒 DSGVO-konform',

    // How It Works
    'howItWorks.title': 'So funktioniert es',
    'howItWorks.subtitle': 'In drei einfachen Schritten zu Ihrem KI-Rezeptionisten',
    'howItWorks.step1.title': 'Geschäftstyp auswählen',
    'howItWorks.step1.desc': 'Wählen Sie Ihre Branche und passen Sie den KI-Assistenten an Ihre Bedürfnisse an.',
    'howItWorks.step2.title': 'KI-Rezeptionisten personalisieren',
    'howItWorks.step2.desc': 'Konfigurieren Sie Antworten, Terminregeln und Gesprächsabläufe individuell.',
    'howItWorks.step3.title': 'In Minuten live gehen',
    'howItWorks.step3.desc': 'Aktivieren Sie Ihren KI-Rezeptionisten und beginnen Sie sofort mit der Automatisierung.',

    // Products
    'products.title': 'Unsere Produkte',
    'products.subtitle': 'Maßgeschneiderte KI-Lösungen für Ihr Unternehmen',
    'products.receptionist.category': 'Kernprodukt',
    'products.receptionist.name': 'KI-Rezeptionist',
    'products.receptionist.desc': 'Automatisierte Anrufannahme, Terminbuchung und Kundenbetreuung rund um die Uhr.',
    'products.gdpr.category': 'Compliance',
    'products.gdpr.name': 'DSGVO-Copilot',
    'products.gdpr.desc': 'Automatisierte Datenschutz-Compliance und Dokumentation für Ihr Unternehmen.',
    'products.esg.category': 'Nachhaltigkeit',
    'products.esg.name': 'ESG-Reporter',
    'products.esg.desc': 'Automatisierte ESG-Berichterstattung und Nachhaltigkeitsanalysen.',
    'products.workflow.category': 'Automatisierung',
    'products.workflow.name': 'KI-Workflow-Automatisierung',
    'products.workflow.desc': 'Intelligente Prozessautomatisierung für wiederkehrende Geschäftsabläufe.',
    'products.learnMore': 'Mehr erfahren',

    // Pricing
    'pricing.title': 'Transparente Preise',
    'pricing.subtitle': 'Wählen Sie den Plan, der zu Ihrem Unternehmen passt. Alle Pläne mit kostenloser Testphase.',
    'pricing.starter': 'Starter',
    'pricing.starterDesc': 'Ideal für kleine Unternehmen und Einzelpraxen.',
    'pricing.starterPrice': '99',
    'pricing.pro': 'Pro',
    'pricing.proDesc': 'Für wachsende Unternehmen mit höherem Volumen.',
    'pricing.proPrice': '249',
    'pricing.enterprise': 'Enterprise',
    'pricing.enterpriseDesc': 'Für große Organisationen mit individuellen Anforderungen.',
    'pricing.enterprisePrice': '499',
    'pricing.mostPopular': 'Am beliebtesten',
    'pricing.month': '/Monat',
    'pricing.cta': 'Kostenlos testen',
    'pricing.trialNote': '14 Tage kostenlos testen — keine Kreditkarte erforderlich',
    'pricing.hostingNote': '🇩🇪 Alle Daten auf deutschen Servern gehostet',
    'pricing.starter.f1': 'Bis zu 100 Anrufe/Monat',
    'pricing.starter.f2': 'KI-Rezeptionist (Basis)',
    'pricing.starter.f3': 'Terminbuchung',
    'pricing.starter.f4': 'E-Mail-Support',
    'pricing.starter.f5': '1 Benutzer',
    'pricing.pro.f1': 'Bis zu 500 Anrufe/Monat',
    'pricing.pro.f2': 'KI-Rezeptionist (Erweitert)',
    'pricing.pro.f3': 'WhatsApp-Integration',
    'pricing.pro.f4': 'Prioritäts-Support',
    'pricing.pro.f5': '5 Benutzer',
    'pricing.pro.f6': 'Erweiterte Analysen',
    'pricing.enterprise.f1': 'Unbegrenzte Anrufe',
    'pricing.enterprise.f2': 'Vollständige KI-Suite',
    'pricing.enterprise.f3': 'Dedizierter Account Manager',
    'pricing.enterprise.f4': 'Individuelle Integrationen',
    'pricing.enterprise.f5': 'Unbegrenzte Benutzer',
    'pricing.enterprise.f6': 'SLA-Garantie',
    'pricing.enterprise.f7': 'White-Label-Option',

    // Why Lucidence
    'why.title': 'Warum Lucidence AI',
    'why.subtitle': 'Vertrauen Sie auf deutsche Qualität und Innovation',
    'why.gdpr.title': '100% DSGVO-sicher',
    'why.gdpr.desc': 'Vollständige Konformität mit europäischen Datenschutzrichtlinien.',
    'why.bilingual.title': 'Zweisprachiger Support',
    'why.bilingual.desc': 'Nahtlose Kommunikation auf Deutsch und Englisch.',
    'why.eu.title': 'EU-Server-Hosting',
    'why.eu.desc': 'Alle Daten werden ausschließlich auf EU-Servern gespeichert.',
    'why.custom.title': 'Individuell trainierte KI',
    'why.custom.desc': 'Auf Ihr Unternehmen zugeschnittene KI-Modelle.',
    'why.instant.title': 'Sofortige Einrichtung',
    'why.instant.desc': 'In wenigen Minuten einsatzbereit, ohne technisches Wissen.',
    'why.availability.title': '24/7 Verfügbarkeit',
    'why.availability.desc': 'Ihr KI-Rezeptionist arbeitet rund um die Uhr, jeden Tag.',

    // Demo
    'demo.title': 'Live-Demo',
    'demo.subtitle': 'Erleben Sie unseren KI-Rezeptionisten in Aktion',
    'demo.tryLive': 'Live-Demo testen',
    'demo.tryCall': 'Sprachanruf testen',
    'demo.tag1': 'Natürliche Gespräche',
    'demo.tag2': 'Auto-Buchung',
    'demo.tag3': 'Mehrsprachig',
    'demo.user1': 'Hallo, ich möchte gerne einen Termin vereinbaren.',
    'demo.ai1': 'Gerne! Ich kann Ihnen folgende Zeiten anbieten: Montag 14:00, Dienstag 10:00 oder Mittwoch 16:00. Welcher Termin passt Ihnen am besten?',
    'demo.user2': 'Dienstag um 10:00 Uhr wäre perfekt.',
    'demo.ai2': 'Wunderbar! Ihr Termin am Dienstag um 10:00 Uhr ist bestätigt. Sie erhalten eine Bestätigung per E-Mail. Kann ich Ihnen noch bei etwas anderem helfen?',

    // Contact
    'contact.title': 'Kontaktieren Sie uns',
    'contact.subtitle': 'Lassen Sie uns gemeinsam Ihre Geschäftsprozesse optimieren',
    'contact.name': 'Vollständiger Name',
    'contact.email': 'Geschäftliche E-Mail',
    'contact.business': 'Unternehmenstyp',
    'contact.requirements': 'Ihre Anforderungen',
    'contact.cta': 'Nachricht senden',
    'contact.privacy': 'Mit dem Absenden stimmen Sie unserer Datenschutzerklärung zu.',
    'contact.directEmail': 'Oder kontaktieren Sie uns direkt: kontakt@lucidence.de',
    'contact.businessTypes.medical': 'Arztpraxis',
    'contact.businessTypes.dental': 'Zahnarztpraxis',
    'contact.businessTypes.legal': 'Anwaltskanzlei',
    'contact.businessTypes.other': 'Sonstiges',

    // Footer
    'footer.desc': 'Lucidence Solutions — KI-gestützte Lösungen für moderne Unternehmen in Deutschland und Europa.',
    'footer.products': 'Produkte',
    'footer.products.receptionist': 'KI-Rezeptionist',
    'footer.products.gdpr': 'DSGVO-Copilot',
    'footer.products.esg': 'ESG-Reporter',
    'footer.products.workflow': 'Workflow-Automatisierung',
    'footer.company': 'Unternehmen',
    'footer.company.about': 'Über uns',
    'footer.company.careers': 'Karriere',
    'footer.company.blog': 'Blog',
    'footer.company.contact': 'Kontakt',
    'footer.contact': 'Kontakt',
    'footer.contact.email': 'kontakt@lucidence.de',
    'footer.contact.phone': '+49 69 123 456 78',
    'footer.contact.address': 'Lucidence Solutions GmbH\nMusterstraße 42\n60311 Frankfurt am Main\nDeutschland',
    'footer.legal.privacy': 'Datenschutz',
    'footer.legal.terms': 'AGB',
    'footer.legal.imprint': 'Impressum',
    'footer.powered': 'Powered by ElevenLabs Agents',
    'footer.copyright': '© {year} Lucidence Solutions GmbH. Alle Rechte vorbehalten.',

    // ===== Login Page =====
    'login.brandHeadline': 'Willkommen zurück bei der',
    'login.brandHighlight': 'KI-Plattform',
    'login.brandDesc': 'Greifen Sie auf Ihren zentralen Authentifizierungs-Hub zu und verwalten Sie Ihre KI-Projekte mit Vertrauen.',
    'login.backToHome': 'Zurück zur Startseite',
    'login.title': 'In Ihr Konto einloggen',
    'login.subtitle': 'Geben Sie Ihre Anmeldedaten ein, um auf Ihr Dashboard zuzugreifen.',
    'login.noAccount': 'Noch kein Konto?',
    'login.applyLead': 'Als Lead bewerben',
    'login.needRegister': 'Müssen Sie sich registrieren?',
    'login.createAccount': 'Konto erstellen',
    'login.email': 'E-Mail',
    'login.password': 'Passwort',
    'login.signIn': 'Anmelden',
    'login.signingIn': 'Wird angemeldet...',
    'login.failed': 'Anmeldung fehlgeschlagen',
    'login.success': 'Anmeldung erfolgreich',
    'login.welcomeBack': 'Willkommen zurück!',

    // ===== Signup Page =====
    'signup.brandHeadline': 'Werden Sie Teil der Zukunft von',
    'signup.brandHighlight': 'KI-gestützten Praxen',
    'signup.brandDesc': 'Bewerben Sie sich als Lucidence-Partner und transformieren Sie Ihre Praxis mit modernsten KI-Lösungen.',
    'signup.feature1': 'Zentralisierte Authentifizierung',
    'signup.feature2': 'Multi-Projekt-Verwaltung',
    'signup.feature3': 'KI-gestützte Dashboards',
    'signup.feature4': 'Engagiertes Support-Team',
    'signup.backToHome': 'Zurück zur Startseite',
    'signup.title': 'Bewerbung erstellen',
    'signup.subtitle': 'Füllen Sie das Formular aus und unser Team wird sich melden.',
    'signup.alreadyAccount': 'Bereits ein Konto?',
    'signup.signIn': 'Anmelden',
    'signup.submitted.title': 'Bewerbung eingereicht!',
    'signup.submitted.desc': 'Vielen Dank für Ihr Interesse an Lucidence. Unser Team wird Ihre Bewerbung prüfen und Sie innerhalb von 24-48 Stunden kontaktieren.',
    'signup.submitted.cta': 'Zurück zur Startseite',
    'signup.fullName': 'Vollständiger Name',
    'signup.email': 'E-Mail',
    'signup.phone': 'Telefonnummer',
    'signup.submit': 'Absenden',
    'signup.submitting': 'Wird gesendet...',
    'signup.successTitle': 'Bewerbung eingereicht',
    'signup.successDesc': 'Vielen Dank! Unser Team wird sich bald bei Ihnen melden.',
    'signup.failedTitle': 'Einreichung fehlgeschlagen',

    // ===== Register Page =====
    'register.brandHeadline': 'Lucidence beitreten',
    'register.brandDesc': 'Erstellen Sie Ihr Konto, um leistungsstarke KI-Projektmanagement-Tools zu nutzen und mit Ihrem Team zusammenzuarbeiten.',
    'register.step1': 'Einzigartigen Benutzernamen erstellen',
    'register.step2': 'E-Mail-Adresse verifizieren',
    'register.step3': 'Projekte verwalten',
    'register.backToHome': 'Zurück zur Startseite',
    'register.title': 'Konto erstellen',
    'register.subtitle': 'Geben Sie Ihre Daten ein, um sich zu registrieren',
    'register.alreadyAccount': 'Bereits ein Konto?',
    'register.signIn': 'Anmelden',
    'register.name': 'Name',
    'register.email': 'E-Mail',
    'register.password': 'Passwort',
    'register.confirmPassword': 'Passwort bestätigen',
    'register.role': 'Rolle',
    'register.roleAdmin': 'Admin',
    'register.roleStaff': 'Mitarbeiter',
    'register.roleClient': 'Kunde',
    'register.submit': 'Registrieren',
    'register.submitting': 'Konto wird erstellt...',
    'register.successTitle': 'Registrierung erfolgreich',
    'register.successDesc': 'Bitte überprüfen Sie Ihre E-Mail, um Ihr Konto zu verifizieren, bevor Sie sich anmelden.',
    'register.failedTitle': 'Registrierung fehlgeschlagen',

    // ===== Register Role Page =====
    'registerRole.title': 'Registrieren',
    'registerRole.subtitle': 'Wählen Sie Ihre Rolle, um fortzufahren',

    // ===== Not Found Page =====
    'notFound.title': '404',
    'notFound.desc': 'Seite nicht gefunden',
    'notFound.link': 'Zurück zur Startseite',

    // ===== Dashboard Layout =====
    'layout.dashboard': 'Dashboard',
    'layout.leads': 'Leads',
    'layout.users': 'Benutzer',
    'layout.projects': 'Projekte',
    'layout.myProjects': 'Meine Projekte',
    'layout.settings': 'Einstellungen',
    'layout.logout': 'Abmelden',
    'layout.exitProject': 'Projekt verlassen',

    // ===== Admin Dashboard =====
    'admin.dashboard.title': 'Admin-Dashboard',
    'admin.dashboard.subtitle': 'Willkommen zurück. Hier ist eine Übersicht Ihrer Plattform.',
    'admin.totalLeads': 'Gesamt-Leads',
    'admin.activeUsers': 'Aktive Benutzer',
    'admin.activeProjects': 'Aktive Projekte',
    'admin.pendingLeads': 'Offene Leads',
    'admin.thisMonth': '+{count} diesen Monat',
    'admin.allTime': 'Gesamtzeit',
    'admin.currentlyActive': 'Aktuell aktiv',
    'admin.clientProjects': 'Kundenprojekte',
    'admin.allProjects': 'Alle Projekte',
    'admin.awaitingReview': 'Warten auf Überprüfung',
    'admin.needAttention': 'Benötigen Aufmerksamkeit',
    'admin.recentLeads': 'Neueste Leads',
    'admin.latestApplications': 'Neueste Bewerbungen warten auf Überprüfung',
    'admin.noLeads': 'Noch keine Leads',
    'admin.quickActions': 'Schnellzugriffe',
    'admin.commonTasks': 'Häufige Verwaltungsaufgaben',
    'admin.reviewLeads': 'Leads prüfen',
    'admin.manageUsers': 'Benutzer verwalten',
    'admin.viewProjects': 'Projekte ansehen',
    'admin.manageClients': 'Kunden verwalten',
    'admin.justNow': 'Gerade eben',
    'admin.hoursAgo': 'vor {count} Stunden',
    'admin.dayAgo': 'vor 1 Tag',
    'admin.daysAgo': 'vor {count} Tagen',

    // ===== Leads Management =====
    'leads.title': 'Leads-Verwaltung',
    'leads.subtitle': 'Eingehende Lead-Bewerbungen prüfen und verwalten.',
    'leads.searchPlaceholder': 'Nach Name, E-Mail oder Unternehmen suchen...',
    'leads.allStatuses': 'Alle Status',
    'leads.pending': 'Ausstehend',
    'leads.contacted': 'Kontaktiert',
    'leads.approved': 'Genehmigt',
    'leads.rejected': 'Abgelehnt',
    'leads.name': 'Name',
    'leads.business': 'Unternehmen',
    'leads.status': 'Status',
    'leads.source': 'Quelle',
    'leads.date': 'Datum',
    'leads.actions': 'Aktionen',
    'leads.loading': 'Leads werden geladen...',
    'leads.noLeads': 'Keine Leads gefunden.',
    'leads.details': 'Lead-Details',
    'leads.detailsDesc': 'Lead-Informationen und Notizen anzeigen.',

    // ===== Users Management =====
    'users.title': 'Benutzerverwaltung',
    'users.clientsTitle': 'Kundenverwaltung',
    'users.staffTitle': 'Mitarbeiterverwaltung',
    'users.adminsTitle': 'Admin-Verwaltung',
    'users.subtitle': 'Alle Benutzerkonten verwalten.',
    'users.clientsSubtitle': 'Registrierte Kundenkonten verwalten.',
    'users.staffSubtitle': 'Mitarbeiterkonten verwalten.',
    'users.adminsSubtitle': 'Administratorkonten verwalten.',
    'users.addUser': 'Benutzer hinzufügen',
    'users.all': 'Alle',
    'users.clients': 'Kunden',
    'users.staff': 'Mitarbeiter',
    'users.admins': 'Admins',
    'users.searchPlaceholder': 'Nach Name oder E-Mail suchen...',
    'users.allStatuses': 'Alle Status',
    'users.active': 'Aktiv',
    'users.disabled': 'Deaktiviert',
    'users.editUser': 'Benutzer bearbeiten',
    'users.sendEmail': 'E-Mail senden',
    'users.delete': 'Löschen',
    'users.noUsers': 'Keine Benutzer gefunden.',

    // ===== Projects Management =====
    'projects.title': 'Kundenprojekte',
    'projects.subtitle': 'KI-Projekte von Kunden verwalten und konfigurieren.',
    'projects.newProject': 'Neues Projekt',
    'projects.searchPlaceholder': 'Projekte suchen...',
    'projects.totalProjects': 'Projekte gesamt',
    'projects.activeProjects': 'Aktive Projekte',
    'projects.setupRequired': 'Einrichtung nötig',
    'projects.configure': 'Konfigurieren',
    'projects.open': 'Öffnen',
    'projects.noProjects': 'Keine Projekte gefunden.',
    'projects.clientProject': 'Kundenprojekt',

    // ===== Staff Dashboard =====
    'staff.dashboard.title': 'Mitarbeiter-Dashboard',
    'staff.dashboard.subtitle': 'Verwalten Sie Ihre zugewiesenen Kundenprojekte.',
    'staff.assignedProjects': 'Zugewiesene Projekte',
    'staff.assignedDesc': 'Projekte, die Sie derzeit verwalten',
    'staff.noProjects': 'Noch keine Projekte zugewiesen.',

    // ===== Client Dashboard =====
    'client.myProjects': 'Meine Projekte',
    'client.selectProject': 'Wählen Sie ein Projekt, um sein Dashboard anzuzeigen',
    'client.refresh': 'Aktualisieren',
    'client.loading': 'Projekte werden geladen...',
    'client.noProjects': 'Keine Projekte gefunden.',
    'client.projectsAppear': 'Ihre Projekte erscheinen hier, sobald sie zugewiesen sind.',
    'client.openDashboard': 'Dashboard öffnen',

    // ===== Project Dashboard (Client internal) =====
    'projDash.dashboard': 'Dashboard',
    'projDash.appointments': 'Termine',
    'projDash.patients': 'Patienten',
    'projDash.reports': 'Berichte',
    'projDash.feedback': 'Feedback',
    'projDash.settings': 'Einstellungen',
    'projDash.doctorPanel': 'Arzt-Panel',
    'projDash.exitProject': 'Projekt verlassen',
    'projDash.search': 'Suchen...',
    'projDash.dashboardTitle': 'Dashboard',
    'projDash.dashboardSubtitle': 'Willkommen zurück! Hier ist eine Übersicht Ihrer Praxis.',
    'projDash.appointmentsTitle': 'Termine',
    'projDash.appointmentsSubtitle': 'Patientenbuchungen und Zeitpläne verwalten.',
    'projDash.patientsTitle': 'Patienten',
    'projDash.patientsSubtitle': 'Patientenakten anzeigen und verwalten.',
    'projDash.reportsTitle': 'Berichte',
    'projDash.reportsSubtitle': 'Analysen und Einblicke für Ihre Praxis.',
    'projDash.feedbackTitle': 'Feedback',
    'projDash.feedbackSubtitle': 'Kundenfeedback aus Ihrem Projekt.',
    'projDash.settingsTitle': 'Einstellungen',
    'projDash.settingsSubtitle': 'Ihre Einstellungen und Ihr Konto konfigurieren.',
    'projDash.loadingData': 'Projektdaten werden geladen...',

    // ===== Stat Cards =====
    'stats.totalPatients': 'Patienten gesamt',
    'stats.newToday': 'Heute neu',
    'stats.existingPatients': 'Bestandspatienten',
    'stats.appointmentsToday': 'Termine heute',

    // ===== Charts =====
    'charts.weeklyTrend': 'Neue vs. Bestandspatienten (Wöchentlich)',
    'charts.newPatients': 'Neue Patienten',
    'charts.existingPatients': 'Bestandspatienten',
    'charts.patientDistribution': 'Patientenverteilung',
    'charts.urgencyEscalation': 'Eskalation nach Dringlichkeit',

    // ===== Recent Patients =====
    'recentPatients.title': 'Neueste Patienten',
    'recentPatients.noPatients': 'Keine Patienten gefunden',
    'recentPatients.noPhone': 'Keine Telefonnummer',

    // ===== Appointments Page =====
    'appointments.allAppointments': 'Alle Termine',
    'appointments.sortBy': 'Sortieren nach',
    'appointments.patientName': 'Patientenname',
    'appointments.dateTime': 'Datum & Uhrzeit',
    'appointments.noAppointments': 'Keine Termine gefunden',
    'appointments.noDate': 'Kein Datum',

    // ===== Patients Page =====
    'patients.allPatients': 'Alle Patienten',
    'patients.patient': 'Patient',
    'patients.phone': 'Telefon',
    'patients.type': 'Typ',
    'patients.status': 'Status',
    'patients.urgency': 'Dringlichkeit',
    'patients.sortName': 'Name',
    'patients.sortDate': 'Hinzugefügt am',
    'patients.sortUrgency': 'Dringlichkeit',
    'patients.sortType': 'Typ',
    'patients.noPatients': 'Keine Patienten gefunden',

    // ===== Feedback Page =====
    'feedback.title': 'Feedback',
    'feedback.entries': 'Einträge',
    'feedback.noFeedback': 'Kein Feedback gefunden',
    'feedback.noFeedbackDesc': 'Feedback-Einträge erscheinen hier, sobald sie eingereicht werden.',
    'feedback.loading': 'Feedback wird geladen...',

    // ===== Settings Pages =====
    'settings.profile': 'Profileinstellungen',
    'settings.profileDesc': 'Kontoinformationen verwalten',
    'settings.firstName': 'Vorname',
    'settings.lastName': 'Nachname',
    'settings.email': 'E-Mail',
    'settings.phone': 'Telefonnummer',
    'settings.saveChanges': 'Änderungen speichern',
    'settings.notifications': 'Benachrichtigungen',
    'settings.notificationsDesc': 'Konfigurieren Sie, wie Sie Benachrichtigungen erhalten',
    'settings.emailNotif': 'E-Mail-Benachrichtigungen',
    'settings.emailNotifDesc': 'E-Mail-Benachrichtigungen für neue Termine erhalten',
    'settings.smsNotif': 'SMS-Benachrichtigungen',
    'settings.smsNotifDesc': 'SMS-Erinnerungen für anstehende Termine erhalten',
    'settings.pushNotif': 'Push-Benachrichtigungen',
    'settings.pushNotifDesc': 'Browser-Push-Benachrichtigungen für Echtzeit-Updates',
    'settings.security': 'Sicherheit',
    'settings.securityDesc': 'Sicherheitseinstellungen verwalten',
    'settings.twoFactor': 'Zwei-Faktor-Authentifizierung',
    'settings.twoFactorDesc': 'Zusätzliche Sicherheitsebene für Ihr Konto hinzufügen',
    'settings.changePassword': 'Passwort ändern',
    'settings.newPassword': 'Neues Passwort',
    'settings.update': 'Aktualisieren',
    'settings.appearance': 'Darstellung',
    'settings.appearanceDesc': 'Aussehen und Verhalten anpassen',
    'settings.darkMode': 'Dunkelmodus',
    'settings.darkModeDesc': 'Zwischen hellen und dunklen Themen wechseln',
    'settings.compactView': 'Kompakte Ansicht',
    'settings.compactViewDesc': 'Mehr Inhalte mit weniger Abstand anzeigen',
    'settings.language': 'Sprache',
    'settings.languageDesc': 'Bevorzugte Sprache für die Benutzeroberfläche',
    'settings.german': 'Deutsch',
    'settings.english': 'Englisch',

    // Admin-specific settings
    'settings.admin.platformTitle': 'Plattformeinstellungen',
    'settings.admin.platformDesc': 'Globale Plattformkonfiguration verwalten',
    'settings.admin.registrations': 'Öffentliche Registrierungen',
    'settings.admin.registrationsDesc': 'Neuen Benutzern die Registrierung ermöglichen',
    'settings.admin.maintenance': 'Wartungsmodus',
    'settings.admin.maintenanceDesc': 'Plattform vorübergehend für Wartungsarbeiten deaktivieren',
    'settings.admin.userManagement': 'Benutzerverwaltung',
    'settings.admin.userManagementDesc': 'Benutzerrollen und Berechtigungen konfigurieren',
    'settings.admin.defaultRole': 'Standard-Benutzerrolle',
    'settings.admin.autoApprove': 'Leads automatisch genehmigen',
    'settings.admin.autoApproveDesc': 'Neue Leads automatisch als Kunden genehmigen',
    'settings.admin.dataRetention': 'Datenaufbewahrung',
    'settings.admin.dataRetentionDesc': 'Datenaufbewahrungsrichtlinien konfigurieren',
    'settings.admin.retentionPeriod': 'Aufbewahrungszeitraum',
    'settings.admin.days30': '30 Tage',
    'settings.admin.days90': '90 Tage',
    'settings.admin.days180': '180 Tage',
    'settings.admin.days365': '1 Jahr',
    'settings.admin.auditLog': 'Audit-Log aktivieren',
    'settings.admin.auditLogDesc': 'Alle administrativen Aktionen protokollieren',

    // Staff-specific settings
    'settings.staff.availability': 'Verfügbarkeit',
    'settings.staff.availabilityDesc': 'Ihre Arbeitszeiten und Verfügbarkeit verwalten',
    'settings.staff.available': 'Verfügbar für neue Projekte',
    'settings.staff.availableDesc': 'Für neue Projektzuweisungen zur Verfügung stehen',
    'settings.staff.workingHours': 'Arbeitszeiten',
    'settings.staff.startTime': 'Startzeit',
    'settings.staff.endTime': 'Endzeit',
    'settings.staff.projectPrefs': 'Projekteinstellungen',
    'settings.staff.projectPrefsDesc': 'Bevorzugte Projekttypen und -größen konfigurieren',
    'settings.staff.maxProjects': 'Maximale gleichzeitige Projekte',
    'settings.staff.projectNotif': 'Projekt-Updates',
    'settings.staff.projectNotifDesc': 'Benachrichtigungen erhalten, wenn Projekte zugewiesen oder aktualisiert werden',

    // Client-specific settings
    'settings.client.business': 'Unternehmensprofil',
    'settings.client.businessDesc': 'Ihre Geschäftsinformationen verwalten',
    'settings.client.businessName': 'Unternehmensname',
    'settings.client.businessAddress': 'Geschäftsadresse',
    'settings.client.businessCity': 'Stadt',
    'settings.client.billing': 'Abrechnung',
    'settings.client.billingDesc': 'Abonnement und Zahlungsinformationen verwalten',
    'settings.client.currentPlan': 'Aktueller Plan',
    'settings.client.upgradePlan': 'Plan upgraden',
    'settings.client.apiAccess': 'API-Zugang',
    'settings.client.apiAccessDesc': 'API-Schlüssel und Integrationseinstellungen verwalten',
    'settings.client.apiKey': 'API-Schlüssel',
    'settings.client.regenerateKey': 'Schlüssel neu generieren',
    'settings.client.webhookUrl': 'Webhook-URL',
    'settings.client.dataExport': 'Datenexport',
    'settings.client.dataExportDesc': 'Ihre Projektdaten exportieren',
    'settings.client.exportAll': 'Alle Daten exportieren',
  },
  en: {
    // Navbar
    'nav.howItWorks': 'How It Works',
    'nav.products': 'Products',
    'nav.pricing': 'Pricing',
    'nav.demo': 'Demo',
    'nav.contact': 'Contact',
    'nav.login': 'Login',
    'nav.getStarted': 'Get Started',

    // Hero
    'hero.headline': 'Never miss a customer again.',
    'hero.subheadline': 'Your 24/7 AI Receptionist — AI-powered, hosted in Germany.',
    'hero.compliance': '100% GDPR compliant',
    'hero.bullet1': 'Phone calls',
    'hero.bullet2': 'WhatsApp & Chat',
    'hero.bullet3': 'Auto booking',
    'hero.cta': 'Book a Demo',
    'hero.trust': '🇩🇪 Hosted in Frankfurt • 🔒 GDPR compliant',

    // How It Works
    'howItWorks.title': 'How It Works',
    'howItWorks.subtitle': 'Get your AI receptionist up and running in three simple steps',
    'howItWorks.step1.title': 'Choose your business type',
    'howItWorks.step1.desc': 'Select your industry and tailor the AI assistant to your needs.',
    'howItWorks.step2.title': 'Customize your AI receptionist',
    'howItWorks.step2.desc': 'Configure responses, scheduling rules, and conversation flows.',
    'howItWorks.step3.title': 'Go live in minutes',
    'howItWorks.step3.desc': 'Activate your AI receptionist and start automating immediately.',

    // Products
    'products.title': 'Our Products',
    'products.subtitle': 'Tailored AI solutions for your business',
    'products.receptionist.category': 'Core Product',
    'products.receptionist.name': 'AI Receptionist',
    'products.receptionist.desc': 'Automated call answering, appointment booking, and customer support around the clock.',
    'products.gdpr.category': 'Compliance',
    'products.gdpr.name': 'GDPR Copilot',
    'products.gdpr.desc': 'Automated data protection compliance and documentation for your business.',
    'products.esg.category': 'Sustainability',
    'products.esg.name': 'ESG Reporter',
    'products.esg.desc': 'Automated ESG reporting and sustainability analytics.',
    'products.workflow.category': 'Automation',
    'products.workflow.name': 'AI Workflow Automation',
    'products.workflow.desc': 'Intelligent process automation for recurring business workflows.',
    'products.learnMore': 'Learn more',

    // Pricing
    'pricing.title': 'Transparent Pricing',
    'pricing.subtitle': 'Choose the plan that fits your business. All plans include a free trial.',
    'pricing.starter': 'Starter',
    'pricing.starterDesc': 'Ideal for small businesses and solo practices.',
    'pricing.starterPrice': '99',
    'pricing.pro': 'Pro',
    'pricing.proDesc': 'For growing businesses with higher volume.',
    'pricing.proPrice': '249',
    'pricing.enterprise': 'Enterprise',
    'pricing.enterpriseDesc': 'For large organizations with custom requirements.',
    'pricing.enterprisePrice': '499',
    'pricing.mostPopular': 'Most Popular',
    'pricing.month': '/month',
    'pricing.cta': 'Start Free Trial',
    'pricing.trialNote': '14-day free trial — no credit card required',
    'pricing.hostingNote': '🇩🇪 All data hosted on German servers',
    'pricing.starter.f1': 'Up to 100 calls/month',
    'pricing.starter.f2': 'AI Receptionist (Basic)',
    'pricing.starter.f3': 'Appointment booking',
    'pricing.starter.f4': 'Email support',
    'pricing.starter.f5': '1 user',
    'pricing.pro.f1': 'Up to 500 calls/month',
    'pricing.pro.f2': 'AI Receptionist (Advanced)',
    'pricing.pro.f3': 'WhatsApp integration',
    'pricing.pro.f4': 'Priority support',
    'pricing.pro.f5': '5 users',
    'pricing.pro.f6': 'Advanced analytics',
    'pricing.enterprise.f1': 'Unlimited calls',
    'pricing.enterprise.f2': 'Full AI suite',
    'pricing.enterprise.f3': 'Dedicated account manager',
    'pricing.enterprise.f4': 'Custom integrations',
    'pricing.enterprise.f5': 'Unlimited users',
    'pricing.enterprise.f6': 'SLA guarantee',
    'pricing.enterprise.f7': 'White-label option',

    // Why Lucidence
    'why.title': 'Why Lucidence AI',
    'why.subtitle': 'Trust in German quality and innovation',
    'why.gdpr.title': '100% GDPR Secure',
    'why.gdpr.desc': 'Full compliance with European data protection regulations.',
    'why.bilingual.title': 'Bilingual Support',
    'why.bilingual.desc': 'Seamless communication in German and English.',
    'why.eu.title': 'EU Server Hosting',
    'why.eu.desc': 'All data stored exclusively on EU servers.',
    'why.custom.title': 'Custom-Trained AI',
    'why.custom.desc': 'AI models tailored to your specific business.',
    'why.instant.title': 'Instant Setup',
    'why.instant.desc': 'Ready in minutes, no technical knowledge required.',
    'why.availability.title': '24/7 Availability',
    'why.availability.desc': 'Your AI receptionist works around the clock, every day.',

    // Demo
    'demo.title': 'Live Demo',
    'demo.subtitle': 'Experience our AI receptionist in action',
    'demo.tryLive': 'Try Live Demo',
    'demo.tryCall': 'Try Voice Call',
    'demo.tag1': 'Natural conversations',
    'demo.tag2': 'Auto booking',
    'demo.tag3': 'Multilingual',
    'demo.user1': 'Hi, I\'d like to schedule an appointment.',
    'demo.ai1': 'Of course! I can offer you the following times: Monday 2:00 PM, Tuesday 10:00 AM, or Wednesday 4:00 PM. Which works best for you?',
    'demo.user2': 'Tuesday at 10:00 AM would be perfect.',
    'demo.ai2': 'Wonderful! Your appointment on Tuesday at 10:00 AM is confirmed. You\'ll receive a confirmation via email. Is there anything else I can help you with?',

    // Contact
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Let\'s optimize your business processes together',
    'contact.name': 'Full Name',
    'contact.email': 'Business Email',
    'contact.business': 'Business Type',
    'contact.requirements': 'Your Requirements',
    'contact.cta': 'Send Message',
    'contact.privacy': 'By submitting, you agree to our Privacy Policy.',
    'contact.directEmail': 'Or contact us directly: kontakt@lucidence.de',
    'contact.businessTypes.medical': 'Medical Practice',
    'contact.businessTypes.dental': 'Dental Practice',
    'contact.businessTypes.legal': 'Law Firm',
    'contact.businessTypes.other': 'Other',

    // Footer
    'footer.desc': 'Lucidence Solutions — AI-powered solutions for modern businesses in Germany and Europe.',
    'footer.products': 'Products',
    'footer.products.receptionist': 'AI Receptionist',
    'footer.products.gdpr': 'GDPR Copilot',
    'footer.products.esg': 'ESG Reporter',
    'footer.products.workflow': 'Workflow Automation',
    'footer.company': 'Company',
    'footer.company.about': 'About Us',
    'footer.company.careers': 'Careers',
    'footer.company.blog': 'Blog',
    'footer.company.contact': 'Contact',
    'footer.contact': 'Contact',
    'footer.contact.email': 'kontakt@lucidence.de',
    'footer.contact.phone': '+49 69 123 456 78',
    'footer.contact.address': 'Lucidence Solutions GmbH\nMusterstraße 42\n60311 Frankfurt am Main\nGermany',
    'footer.legal.privacy': 'Privacy',
    'footer.legal.terms': 'Terms',
    'footer.legal.imprint': 'Imprint',
    'footer.powered': 'Powered by ElevenLabs Agents',
    'footer.copyright': '© {year} Lucidence Solutions GmbH. All rights reserved.',

    // ===== Login Page =====
    'login.brandHeadline': 'Welcome back to the',
    'login.brandHighlight': 'AI Platform',
    'login.brandDesc': 'Access your centralized authentication hub and manage your AI projects with confidence.',
    'login.backToHome': 'Back to home',
    'login.title': 'Sign in to your account',
    'login.subtitle': 'Enter your credentials to access your dashboard.',
    'login.noAccount': 'Don\'t have an account?',
    'login.applyLead': 'Apply as a lead',
    'login.needRegister': 'Need to register?',
    'login.createAccount': 'Create account',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.signIn': 'Sign in',
    'login.signingIn': 'Signing in...',
    'login.failed': 'Login failed',
    'login.success': 'Login successful',
    'login.welcomeBack': 'Welcome back!',

    // ===== Signup Page =====
    'signup.brandHeadline': 'Join the future of',
    'signup.brandHighlight': 'AI-powered clinics',
    'signup.brandDesc': 'Apply to become a Lucidence partner and transform your practice with cutting-edge AI solutions.',
    'signup.feature1': 'Centralized authentication',
    'signup.feature2': 'Multi-project management',
    'signup.feature3': 'AI-powered dashboards',
    'signup.feature4': 'Dedicated support team',
    'signup.backToHome': 'Back to home',
    'signup.title': 'Create your application',
    'signup.subtitle': 'Fill out the form below and our team will get in touch.',
    'signup.alreadyAccount': 'Already have an account?',
    'signup.signIn': 'Sign in',
    'signup.submitted.title': 'Application Submitted!',
    'signup.submitted.desc': 'Thank you for your interest in Lucidence. Our team will review your application and contact you within 24-48 hours.',
    'signup.submitted.cta': 'Return to Home',
    'signup.fullName': 'Full Name',
    'signup.email': 'Email',
    'signup.phone': 'Phone Number',
    'signup.submit': 'Submit',
    'signup.submitting': 'Submitting...',
    'signup.successTitle': 'Application submitted',
    'signup.successDesc': 'Thank you! Our team will contact you soon.',
    'signup.failedTitle': 'Submission failed',

    // ===== Register Page =====
    'register.brandHeadline': 'Join Lucidence',
    'register.brandDesc': 'Create your account to access powerful AI project management tools and collaborate with your team.',
    'register.step1': 'Create your unique username',
    'register.step2': 'Verify your email address',
    'register.step3': 'Start managing your projects',
    'register.backToHome': 'Back to home',
    'register.title': 'Create Account',
    'register.subtitle': 'Enter your details to register',
    'register.alreadyAccount': 'Already have an account?',
    'register.signIn': 'Sign in',
    'register.name': 'Name',
    'register.email': 'Email',
    'register.password': 'Password',
    'register.confirmPassword': 'Confirm Password',
    'register.role': 'Role',
    'register.roleAdmin': 'Admin',
    'register.roleStaff': 'Staff',
    'register.roleClient': 'Client',
    'register.submit': 'Register',
    'register.submitting': 'Creating Account...',
    'register.successTitle': 'Registration Successful',
    'register.successDesc': 'Please check your email to verify your account before logging in.',
    'register.failedTitle': 'Registration failed',

    // ===== Register Role Page =====
    'registerRole.title': 'Register',
    'registerRole.subtitle': 'Select your role to continue',

    // ===== Not Found Page =====
    'notFound.title': '404',
    'notFound.desc': 'Oops! Page not found',
    'notFound.link': 'Return to Home',

    // ===== Dashboard Layout =====
    'layout.dashboard': 'Dashboard',
    'layout.leads': 'Leads',
    'layout.users': 'Users',
    'layout.projects': 'Projects',
    'layout.myProjects': 'My Projects',
    'layout.settings': 'Settings',
    'layout.logout': 'Log out',
    'layout.exitProject': 'Exit Project',

    // ===== Admin Dashboard =====
    'admin.dashboard.title': 'Admin Dashboard',
    'admin.dashboard.subtitle': 'Welcome back. Here\'s an overview of your platform.',
    'admin.totalLeads': 'Total Leads',
    'admin.activeUsers': 'Active Users',
    'admin.activeProjects': 'Active Projects',
    'admin.pendingLeads': 'Pending Leads',
    'admin.thisMonth': '+{count} this month',
    'admin.allTime': 'All time',
    'admin.currentlyActive': 'Currently active',
    'admin.clientProjects': 'Client projects',
    'admin.allProjects': 'All projects',
    'admin.awaitingReview': 'Awaiting review',
    'admin.needAttention': 'Need attention',
    'admin.recentLeads': 'Recent Leads',
    'admin.latestApplications': 'Latest applications awaiting review',
    'admin.noLeads': 'No leads yet',
    'admin.quickActions': 'Quick Actions',
    'admin.commonTasks': 'Common administrative tasks',
    'admin.reviewLeads': 'Review Leads',
    'admin.manageUsers': 'Manage Users',
    'admin.viewProjects': 'View Projects',
    'admin.manageClients': 'Manage Clients',
    'admin.justNow': 'Just now',
    'admin.hoursAgo': '{count} hours ago',
    'admin.dayAgo': '1 day ago',
    'admin.daysAgo': '{count} days ago',

    // ===== Leads Management =====
    'leads.title': 'Leads Management',
    'leads.subtitle': 'Review and manage incoming lead applications.',
    'leads.searchPlaceholder': 'Search by name, email, or business...',
    'leads.allStatuses': 'All Statuses',
    'leads.pending': 'Pending',
    'leads.contacted': 'Contacted',
    'leads.approved': 'Approved',
    'leads.rejected': 'Rejected',
    'leads.name': 'Name',
    'leads.business': 'Business',
    'leads.status': 'Status',
    'leads.source': 'Source',
    'leads.date': 'Date',
    'leads.actions': 'Actions',
    'leads.loading': 'Loading leads...',
    'leads.noLeads': 'No leads found.',
    'leads.details': 'Lead Details',
    'leads.detailsDesc': 'View lead information and notes.',

    // ===== Users Management =====
    'users.title': 'Users Management',
    'users.clientsTitle': 'Clients Management',
    'users.staffTitle': 'Staff Management',
    'users.adminsTitle': 'Admins Management',
    'users.subtitle': 'Manage all user accounts.',
    'users.clientsSubtitle': 'Manage registered client accounts.',
    'users.staffSubtitle': 'Manage staff member accounts.',
    'users.adminsSubtitle': 'Manage administrator accounts.',
    'users.addUser': 'Add User',
    'users.all': 'All',
    'users.clients': 'Clients',
    'users.staff': 'Staff',
    'users.admins': 'Admins',
    'users.searchPlaceholder': 'Search by name or email...',
    'users.allStatuses': 'All Statuses',
    'users.active': 'Active',
    'users.disabled': 'Disabled',
    'users.editUser': 'Edit User',
    'users.sendEmail': 'Send Email',
    'users.delete': 'Delete',
    'users.noUsers': 'No users found.',

    // ===== Projects Management =====
    'projects.title': 'Client Projects',
    'projects.subtitle': 'Manage and configure client AI projects.',
    'projects.newProject': 'New Project',
    'projects.searchPlaceholder': 'Search projects...',
    'projects.totalProjects': 'Total Projects',
    'projects.activeProjects': 'Active Projects',
    'projects.setupRequired': 'Setup Required',
    'projects.configure': 'Configure',
    'projects.open': 'Open',
    'projects.noProjects': 'No projects found.',
    'projects.clientProject': 'Client project',

    // ===== Staff Dashboard =====
    'staff.dashboard.title': 'Staff Dashboard',
    'staff.dashboard.subtitle': 'Manage your assigned client projects.',
    'staff.assignedProjects': 'Assigned Projects',
    'staff.assignedDesc': 'Projects you\'re currently managing',
    'staff.noProjects': 'No projects assigned yet.',

    // ===== Client Dashboard =====
    'client.myProjects': 'My Projects',
    'client.selectProject': 'Select a project to view its dashboard',
    'client.refresh': 'Refresh',
    'client.loading': 'Loading projects...',
    'client.noProjects': 'No projects found.',
    'client.projectsAppear': 'Your projects will appear here once they are assigned.',
    'client.openDashboard': 'Open Dashboard',

    // ===== Project Dashboard (Client internal) =====
    'projDash.dashboard': 'Dashboard',
    'projDash.appointments': 'Appointments',
    'projDash.patients': 'Patients',
    'projDash.reports': 'Reports',
    'projDash.feedback': 'Feedback',
    'projDash.settings': 'Settings',
    'projDash.doctorPanel': 'Doctor Panel',
    'projDash.exitProject': 'Exit Project',
    'projDash.search': 'Search...',
    'projDash.dashboardTitle': 'Dashboard',
    'projDash.dashboardSubtitle': 'Welcome back! Here\'s an overview of your practice.',
    'projDash.appointmentsTitle': 'Appointments',
    'projDash.appointmentsSubtitle': 'Manage patient bookings and schedules.',
    'projDash.patientsTitle': 'Patients',
    'projDash.patientsSubtitle': 'View and manage your patient records.',
    'projDash.reportsTitle': 'Reports',
    'projDash.reportsSubtitle': 'Analytics and insights for your practice.',
    'projDash.feedbackTitle': 'Feedback',
    'projDash.feedbackSubtitle': 'Customer feedback from your project.',
    'projDash.settingsTitle': 'Settings',
    'projDash.settingsSubtitle': 'Configure your preferences and account.',
    'projDash.loadingData': 'Loading project data...',

    // ===== Stat Cards =====
    'stats.totalPatients': 'Total Patients',
    'stats.newToday': 'New Today',
    'stats.existingPatients': 'Existing Patients',
    'stats.appointmentsToday': 'Appointments Today',

    // ===== Charts =====
    'charts.weeklyTrend': 'New vs Existing Patients (Weekly)',
    'charts.newPatients': 'New Patients',
    'charts.existingPatients': 'Existing Patients',
    'charts.patientDistribution': 'Patient Distribution',
    'charts.urgencyEscalation': 'Escalation by Urgency',

    // ===== Recent Patients =====
    'recentPatients.title': 'Recent Patients',
    'recentPatients.noPatients': 'No patients found',
    'recentPatients.noPhone': 'No phone',

    // ===== Appointments Page =====
    'appointments.allAppointments': 'All Appointments',
    'appointments.sortBy': 'Sort by',
    'appointments.patientName': 'Patient Name',
    'appointments.dateTime': 'Date & Time',
    'appointments.noAppointments': 'No appointments found',
    'appointments.noDate': 'No date',

    // ===== Patients Page =====
    'patients.allPatients': 'All Patients',
    'patients.patient': 'Patient',
    'patients.phone': 'Phone',
    'patients.type': 'Type',
    'patients.status': 'Status',
    'patients.urgency': 'Urgency',
    'patients.sortName': 'Name',
    'patients.sortDate': 'Date Added',
    'patients.sortUrgency': 'Urgency',
    'patients.sortType': 'Type',
    'patients.noPatients': 'No patients found',

    // ===== Feedback Page =====
    'feedback.title': 'Feedback',
    'feedback.entries': 'entries',
    'feedback.noFeedback': 'No feedback found',
    'feedback.noFeedbackDesc': 'Feedback entries will appear here once submitted.',
    'feedback.loading': 'Loading feedback...',

    // ===== Settings Pages =====
    'settings.profile': 'Profile Settings',
    'settings.profileDesc': 'Manage your account information',
    'settings.firstName': 'First Name',
    'settings.lastName': 'Last Name',
    'settings.email': 'Email',
    'settings.phone': 'Phone Number',
    'settings.saveChanges': 'Save Changes',
    'settings.notifications': 'Notification Preferences',
    'settings.notificationsDesc': 'Configure how you receive notifications',
    'settings.emailNotif': 'Email Notifications',
    'settings.emailNotifDesc': 'Receive email alerts for new appointments',
    'settings.smsNotif': 'SMS Notifications',
    'settings.smsNotifDesc': 'Get SMS reminders for upcoming appointments',
    'settings.pushNotif': 'Push Notifications',
    'settings.pushNotifDesc': 'Browser push notifications for real-time updates',
    'settings.security': 'Security',
    'settings.securityDesc': 'Manage your security settings',
    'settings.twoFactor': 'Two-Factor Authentication',
    'settings.twoFactorDesc': 'Add an extra layer of security to your account',
    'settings.changePassword': 'Change Password',
    'settings.newPassword': 'New password',
    'settings.update': 'Update',
    'settings.appearance': 'Appearance',
    'settings.appearanceDesc': 'Customize the look and feel',
    'settings.darkMode': 'Dark Mode',
    'settings.darkModeDesc': 'Switch between light and dark themes',
    'settings.compactView': 'Compact View',
    'settings.compactViewDesc': 'Show more content with less spacing',
    'settings.language': 'Language',
    'settings.languageDesc': 'Preferred language for the interface',
    'settings.german': 'German',
    'settings.english': 'English',

    // Admin-specific settings
    'settings.admin.platformTitle': 'Platform Settings',
    'settings.admin.platformDesc': 'Manage global platform configuration',
    'settings.admin.registrations': 'Public Registrations',
    'settings.admin.registrationsDesc': 'Allow new users to register',
    'settings.admin.maintenance': 'Maintenance Mode',
    'settings.admin.maintenanceDesc': 'Temporarily disable the platform for maintenance',
    'settings.admin.userManagement': 'User Management',
    'settings.admin.userManagementDesc': 'Configure user roles and permissions',
    'settings.admin.defaultRole': 'Default User Role',
    'settings.admin.autoApprove': 'Auto-Approve Leads',
    'settings.admin.autoApproveDesc': 'Automatically approve new leads as clients',
    'settings.admin.dataRetention': 'Data Retention',
    'settings.admin.dataRetentionDesc': 'Configure data retention policies',
    'settings.admin.retentionPeriod': 'Retention Period',
    'settings.admin.days30': '30 Days',
    'settings.admin.days90': '90 Days',
    'settings.admin.days180': '180 Days',
    'settings.admin.days365': '1 Year',
    'settings.admin.auditLog': 'Enable Audit Log',
    'settings.admin.auditLogDesc': 'Log all administrative actions',

    // Staff-specific settings
    'settings.staff.availability': 'Availability',
    'settings.staff.availabilityDesc': 'Manage your working hours and availability',
    'settings.staff.available': 'Available for New Projects',
    'settings.staff.availableDesc': 'Be available for new project assignments',
    'settings.staff.workingHours': 'Working Hours',
    'settings.staff.startTime': 'Start Time',
    'settings.staff.endTime': 'End Time',
    'settings.staff.projectPrefs': 'Project Preferences',
    'settings.staff.projectPrefsDesc': 'Configure preferred project types and sizes',
    'settings.staff.maxProjects': 'Max Concurrent Projects',
    'settings.staff.projectNotif': 'Project Updates',
    'settings.staff.projectNotifDesc': 'Get notified when projects are assigned or updated',

    // Client-specific settings
    'settings.client.business': 'Business Profile',
    'settings.client.businessDesc': 'Manage your business information',
    'settings.client.businessName': 'Business Name',
    'settings.client.businessAddress': 'Business Address',
    'settings.client.businessCity': 'City',
    'settings.client.billing': 'Billing',
    'settings.client.billingDesc': 'Manage subscription and payment information',
    'settings.client.currentPlan': 'Current Plan',
    'settings.client.upgradePlan': 'Upgrade Plan',
    'settings.client.apiAccess': 'API Access',
    'settings.client.apiAccessDesc': 'Manage API keys and integration settings',
    'settings.client.apiKey': 'API Key',
    'settings.client.regenerateKey': 'Regenerate Key',
    'settings.client.webhookUrl': 'Webhook URL',
    'settings.client.dataExport': 'Data Export',
    'settings.client.dataExportDesc': 'Export your project data',
    'settings.client.exportAll': 'Export All Data',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const stored = localStorage.getItem('lucidence-language');
    return (stored as Language) || 'de';
  });

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('lucidence-language', lang);
  };

  const t = (key: string): string => {
    const value = translations[language][key];
    if (!value) return key;
    return value.replace('{year}', new Date().getFullYear().toString());
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
